settings:
  title: 'Charging Courses Status Page'
  url: 'https://status.chargingcourses.com' # used for Slack messages
  logo: logo-256x256.png # image in ./public/ folder
  daysInHistogram: 90 # number of days you want to display in histogram
  collectResponseTimes: true # collects avg response times from CRON locations

  allmonitorsOperational: 'All Systems Operational'
  notAllmonitorsOperational: 'Not All Systems Operational'
  monitorLabelOperational: 'Operational'
  monitorLabelNotOperational: 'Not Operational'
  monitorLabelNoData: 'No data'
  dayInHistogramNoData: 'No data'
  dayInHistogramOperational: 'All good'
  dayInHistogramNotOperational: ' incident(s)' # xx incident(s) recorded

monitors:
  - id: www-chargingcourses-com # unique identifier
    name: www.chargingcourses.com
    description: 'Charging Courses learning platform.' # default=empty
    url: 'https://chargingcourses.com/' # URL to fetch
    method: GET # default=GET
    expectStatus: 200 # operational status, default=200
    followRedirect: false # should fetch follow redirects, default=false
    linkable: false # allows the title to be a link, default=true

  - id: labs-chargingcourses-com
    name: labs.chargingcourses.com
    description: 'Charging Courses Labs, code anywhere and anything.'
    url: 'https://labs.chargingcourses.com'
    method: GET
    expectStatus: 200
    followRedirect: false # should fetch follow redirects, default=false
    linkable: true # allows the title to be a link, default=true

  - id: auth-chargingcourses-com
    name: auth.chargingcourses.com
    description: 'Charging Courses Authentication, central login for all of our services.'
    url: 'https://auth.chargingcourses.com'
    method: GET
    expectStatus: 200
    followRedirect: false # should fetch follow redirects, default=false
    linkable: true # allows the title to be a link, default=true